# Generated by Django 4.1.5 on 2023-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Fee',
            field=models.IntegerField(),
        ),
    ]
