# Generated by Django 4.1.5 on 2023-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='6FBE6', editable=False, max_length=10),
        ),
    ]
