# Generated by Django 4.1.5 on 2023-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='salary',
        ),
        migrations.AlterField(
            model_name='administration',
            name='unique_id',
            field=models.CharField(default='A8CBC', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='EAC6E', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='3797A', editable=False, max_length=10),
        ),
    ]
