# Generated by Django 4.1.5 on 2023-06-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0002_remove_administration_basic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='unique_id',
            field=models.CharField(default='725EF', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='29EE8', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='44420', editable=False, max_length=10),
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
