# Generated by Django 4.1.5 on 2023-01-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0002_alter_fees_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='basic',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='schoolmgt.subjectb'),
        ),
    ]
