# Generated by Django 4.1.5 on 2023-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0002_remove_teacher_subject_alter_teacher_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='A23C2', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='Subject', to='schoolmgt.subjectb'),
        ),
    ]
