# Generated by Django 4.1.5 on 2023-01-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0003_subjectb_basic_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='basic',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=34, max_length=16),
            preserve_default=False,
        ),
    ]
