# Generated by Django 4.1.5 on 2023-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0003_remove_teacher_subject_alter_teacher_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='5A2D3', editable=False, max_length=10),
        ),
    ]
