# Generated by Django 4.1.5 on 2023-06-01 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0003_alter_administration_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='unique_id',
            field=models.CharField(default='D1EF1', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='BCB7D', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='A7293', editable=False, max_length=10),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('admin', 'admin'), ('parent', 'parent')], max_length=50)),
                ('title', models.TextField(max_length=150)),
                ('body', models.TextField()),
                ('data', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
