# Generated by Django 4.1.5 on 2023-05-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0003_remove_student_gender_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmgt.basic'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='399AB', editable=False, max_length=10),
        ),
    ]
