# Generated by Django 4.1.5 on 2023-06-01 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0003_alter_student_status_alter_student_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='42831', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='FEC12', editable=False, max_length=10),
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(default='testimon.png', null=True, upload_to='firststep')),
                ('unique_id', models.CharField(default='2683F', editable=False, max_length=10)),
                ('basic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmgt.basic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
