# Generated by Django 4.1.5 on 2023-05-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0004_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='CBDDD', editable=False, max_length=10),
        ),
    ]
