# Generated by Django 4.1.5 on 2023-01-24 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0004_remove_teacher_basic_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmgt.basic'),
        ),
    ]
