# Generated by Django 4.1.5 on 2023-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0004_alter_student_basic_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='A8E26', editable=False, max_length=10),
        ),
    ]
