# Generated by Django 4.1.5 on 2023-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0005_alter_teacher_image_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='15AE9', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='testimon.png', null=True, upload_to='firststep'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='43242', editable=False, max_length=10),
        ),
    ]
