# Generated by Django 4.1.5 on 2023-01-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0005_teacher_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentS_name',
            field=models.CharField(default='john', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
    ]
