# Generated by Django 4.1.5 on 2023-05-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0005_teacher_qualifications_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='9B35C', editable=False, max_length=10),
        ),
    ]
