# Generated by Django 4.1.5 on 2023-05-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0006_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='35974', editable=False, max_length=10),
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='testimon.png', null=True, upload_to='')),
                ('basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmgt.basic')),
            ],
        ),
    ]
