# Generated by Django 4.1.5 on 2023-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0007_alter_teacher_unique_id_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='9E24E', editable=False, max_length=10),
        ),
    ]
