# Generated by Django 4.1.5 on 2023-05-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0007_student_bio_alter_student_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='subject',
        ),
        migrations.AddField(
            model_name='total',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolmgt.basic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='D2C28', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='996A8', editable=False, max_length=10),
        ),
    ]
