# Generated by Django 4.1.5 on 2023-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0008_remove_total_subject_total_basic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='66F12', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='CC322', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
