# Generated by Django 4.1.5 on 2023-05-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0008_alter_teacher_bio_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='719CB', editable=False, max_length=10),
        ),
    ]
