# Generated by Django 4.1.5 on 2023-01-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0009_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='basic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmgt.basic'),
        ),
    ]
