# Generated by Django 4.1.5 on 2023-05-30 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0009_alter_student_unique_id_alter_teacher_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catestexam',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='A481F', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='7412B', editable=False, max_length=10),
        ),
    ]
