# Generated by Django 4.1.5 on 2023-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0009_alter_teacher_unique_id_total_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='672CE', editable=False, max_length=10),
        ),
    ]
