# Generated by Django 4.1.5 on 2023-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0010_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='B5127', editable=False, max_length=10),
        ),
    ]
