# Generated by Django 4.1.5 on 2023-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0011_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='testimon.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='testimon.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='1A2A9', editable=False, max_length=10),
        ),
    ]
