# Generated by Django 4.1.5 on 2023-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0011_alter_student_birthday_alter_student_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='A5915', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='CCB45', editable=False, max_length=10),
        ),
    ]
