# Generated by Django 4.1.5 on 2023-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0013_alter_teacher_image_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='72AB5', editable=False, max_length=10),
        ),
    ]
