# Generated by Django 4.1.5 on 2023-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgt', '0014_alter_teacher_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='35D86', editable=False, max_length=10),
        ),
    ]
